<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadMLine" id="000000002bb90ea8" desc="IAcadMLine: IAcadMLine Interface" Application="IAcadApplication 000000013fb02308" Coordinates="(9.15538 14.989 0.0 18.7947 10.0057 0.0 ... )" Document="IAcadDocument 0000000035f28bc8" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000363a8a58" Justification="0" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" MLineScale="1.0" ObjectID="58" ObjectID32="58" ObjectName="AcDbMline" OwnerID="59" OwnerID32="59" PlotStyleName="ByLayer" StyleName="STANDARD" TrueColor="IAcadAcCmColor 00000000363a8ab0" Visible="-1" />
</DwgData>