<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadSpline" id="0000000036da96a8" desc="IAcadSpline: AutoCAD Spline Interface" Application="IAcadApplication 000000013fdf2308" Area="20.1091" Closed="0" Closed2="0" ControlPoints="(28.059 8.80677 0.0 33.9643 7.72128 0.0 ... )" Degree="3" Degree2="3" Document="IAcadDocument 0000000036d35458" EndTangent="(0.0 0.0 0.0)" EntityTransparency="ByLayer" FitPoints="(28.059 8.80677 0.0 40.0613 6.22149 0.0 ... )" FitTolerance="1.0e-010" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a5e91f8" IsPeriodic="0" IsPlanar="-1" IsRational="0" KnotParameterization="0" Knots="(0.0 0.0 0.0 0.0 12.2776 26.0835 ... )" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" NumberOfControlPoints="5" NumberOfFitPoints="3" ObjectID="72" ObjectID32="72" ObjectName="AcDbSpline" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" SplineFrame="1" SplineMethod="0" StartTangent="(0.0 0.0 0.0)" TrueColor="IAcadAcCmColor 000000003a5e1090" Visible="-1" Weights="AutoCAD.Application: No weights available for polynomial spline" />
</DwgData>