<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcad3DPolyline" id="000000002b8d12e8" desc="IAcad3DPolyline: AutoCAD 3dPolyline Interface" Application="IAcadApplication 000000013fca2308" Closed="0" Coordinate="...Indexed contents not shown..." Coordinates="(21.4409 14.6498 0.0 20.8962 5.65378 0.0 ... )" Document="IAcadDocument 0000000038764218" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003b4e18e8" Layer="0" Length="38.6446" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="66" ObjectID32="66" ObjectName="AcDb3dPolyline" OwnerID="67" OwnerID32="67" PlotStyleName="ByLayer" TrueColor="IAcadAcCmColor 000000003b4e1ac0" Type="0" Visible="-1" />
</DwgData>