<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadArc" id="000000002befd868" desc="IAcadArc: AutoCAD Arc Interface" Application="IAcadApplication 000000013fca2308" ArcLength="48.096" Area="215.424" Center="(-18.1933 6.68652 0.0)" Document="IAcadDocument 000000002b8fad38" EndAngle="1.51876" EndPoint="(-17.762 14.9684 0.0)" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e2d1828" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="42" ObjectID32="42" ObjectName="AcDbArc" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" Radius="8.2931" StartAngle="2.00242" StartPoint="(-21.6627 14.219 0.0)" Thickness="0.0" TotalAngle="5.79952" TrueColor="IAcadAcCmColor 000000002e2d19a0" Visible="-1" />
</DwgData>