<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadHelix" id="000000002bb90198" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013fb02308" BaseRadius="1.36885" Constrain="1" Document="IAcadDocument 000000002e85d628" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 0000000035c72478" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="54" ObjectID32="54" ObjectName="AcDbHelix" OwnerID="55" OwnerID32="55" PlotStyleName="ByLayer" Position="(2.25405 13.3778 0.0)" TopRadius="6.82783" TotalLength="77.4916" TrueColor="IAcadAcCmColor 0000000035c726b0" TurnHeight="0.333333" Turns="3.0" TurnSlope="1.38962" Twist="0" Visible="-1" />
</DwgData>