<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadRay" id="000000002bb92088" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013fb02308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.0 -1.0 0.0)" Document="IAcadDocument 0000000039fd11c8" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a223e48" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="68" ObjectID32="68" ObjectName="AcDbRay" OwnerID="69" OwnerID32="69" PlotStyleName="ByLayer" SecondPoint="(10.0931 9.19308 0.0)" TrueColor="IAcadAcCmColor 000000003a224380" Visible="-1" />
</DwgData>