<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadMText" id="000000003aa99318" desc="IAcadMText: AutoCAD MText Interface" Application="IAcadApplication 000000013fdf2308" AttachmentPoint="1" BackgroundFill="0" Document="IAcadDocument 000000003a6d4828" DrawingDirection="5" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Height="0.2" Hyperlinks="IAcadHyperlinks 000000003ef44518" InsertionPoint="(7.33298 14.1158 0.0)" Layer="0" LineSpacingDistance="0.333333" LineSpacingFactor="1.0" LineSpacingStyle="1" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="76" ObjectID32="76" ObjectName="AcDbMText" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" Rotation="0.0" StyleName="Standard" TextString="This a multiline text to check if libredwg is able to read this in the current file format version" TrueColor="IAcadAcCmColor 000000003ef44870" Visible="-1" Width="13.0319" />
</DwgData>