<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadEllipse" id="000000002b736eb8" desc="IAcadEllipse: AutoCAD Ellipse Interface" Application="IAcadApplication 000000013f9c2308" Area="149.024" Center="(11.1433 9.5374 0.0)" Document="IAcadDocument 000000002b75d6e8" EndAngle="6.28319" EndParameter="6.28319" EndPoint="(2.39246 1.50274 0.0)" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002ec9d138" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" MajorAxis="(-8.7508 -8.03465 0.0)" MajorRadius="11.8799" Material="ByLayer" MinorAxis="(2.70052 -2.94122 0.0)" MinorRadius="3.99294" Normal="(0.0 0.0 1.0)" ObjectID="42" ObjectID32="42" ObjectName="AcDbEllipse" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" RadiusRatio="0.336109" StartAngle="0.0" StartParameter="0.0" StartPoint="(2.39246 1.50274 0.0)" TrueColor="IAcadAcCmColor 000000002ec9d310" Visible="-1" />
</DwgData>