<?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadHelix" id="000000002b0ef308" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013ffc2308" BaseRadius="1.36885" Constrain="1" Document="IAcadDocument 000000002e9cb948" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 000000002ede5628" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="48" ObjectID32="48" ObjectName="AcDbHelix" OwnerID="49" OwnerID32="49" PlotStyleName="ByLayer" Position="(2.25405 13.3778 0.0)" TopRadius="6.82783" TotalLength="77.4916" TrueColor="IAcadAcCmColor 000000002ede6400" TurnHeight="0.333333" Turns="3.0" TurnSlope="1.38962" Twist="0" Visible="-1" />
</DwgData>